#!/usr/bin/env bash
# a bash script that accepts 4 arguments to transfer a file to the server
#   The path to the file to be transferred
#   The IP of the server we want to transfer the file to
#   The username scp connects with
#   The path to the SSH private key that scp uses

args=$#

if (( args != 4 ))
then
    echo -e "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY\n"
else

    scp -i "$4" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$1" "$3"@"$2":~/
fi
