#!/usr/bin/env bash
# make redirection “301 Moved Permanently” to https://www.youtube.com/watch?v=QH2-TGUlwu4

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;

        location / {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}" > /etc/nginx/sites-available/default
service nginx restart
