#!/usr/bin/env bash
# inatall HAPROXY on the server and configure it to send travffic to two servers

sudo apt-get -y update && sudo apt-get install -y haproxy
if haproxy -v &> /dev/null; then
        cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
        cat <<EOF > /etc/haproxy/haproxy.cfg
frontend web
    bind *:80
    mode http
    timeout server 30s
    default_backend web_servers

backend web_servers
    balance roundrobin
    mode http
    timeout server 30s
    server web-01 54.160.73.119:80  check
    server web-02 54.234.68.76:80 check
EOF
        sudo service haproxy restart
fi

