#!/usr/bin/env bash
# setup an Ubuntu server as an nginx webserver listening on port 80

apt update
apt -y install nginx
# rm /etc/nginx/sites-enabled/default
# ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
