#!/usr/bin/env bash
# a Bash script that displays To infinity and beyond indefinitely.
# Trap SIGTERM and print I am invincible!!!
trap "echo I am invincible!!!" SIGTERM
while true
do
        echo "To infinity and beyond"
        sleep 2
done