#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS

IFS=":"
while read -r USERNAME PASSWORD USERID GROUP_ID INFO HOME_DIRECTORY SHELL
do 
	echo "The user $USERNAME is part of the $GROUP_ID gang,"\
	"lives in $HOME_DIRECTORY and rides $SHELL. $USERID's place is protected"\
	"by the passcode $PASSWORD, more info about the user here: $INFO"
done < /etc/passwd
unset IFS
