#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Displays the IP and HTTP status code sorted on the numbers of occurneces

awk '{print $1, $9}' apache-access.log | sort -n |uniq -c |sort -rn
