#!/usr/bin/env bash
# A Bash script to configure nginx to run as user nginx and listen on all active IPs on port 8080
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/ 8080/;/' /etc/nginx/sites-available/default
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start

